UI.Web/ViewModels/StockMovimientos/StockMovimientoAgregarViewModel.cs
using Modelos;
using System;
using System.ComponentModel.DataAnnotations;


namespace UI.Web.ViewModels.StockMovimientos

{
    public class StockMovimientoAgregarViewModel
    {
        [Display(Name = "Cantidad")]
        [Required(ErrorMessage = "Cantidad es Requerido")]
        public decimal Cantidad { get; set; }

        [Display(Name = "Motivo")]
        [Required(ErrorMessage = "Motivo es Requerido")]
        public int TipoMovimientoStockID { get; set; }
        public virtual TipoMovimientoStock Motivo { get; set; }

        [Display(Name = "Artículo")]
        [Required(ErrorMessage = "Articulo es Requerido")]
        public int ArticuloID { get; set; }

        public StockMovimiento Mapear()
        {
            StockMovimiento StockMovimiento = new StockMovimiento();

            StockMovimiento.Fecha = DateTime.Now;
            StockMovimiento.Cantidad = Cantidad;
            StockMovimiento.TipoMovimientoStockID = TipoMovimientoStockID;
            StockMovimiento.ArticuloID = ArticuloID;
            var usuario = (Usuario)System.Web.HttpContext.Current.Session["UsuarioActual"];
            StockMovimiento.UsuarioID = usuario.Id;

            return StockMovimiento;
        }
    }
}

UI.Web/Controllers/ArticulosController.cs
using BarcodeLib;
using Modelos;
using Servicios;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Web.Util;
using UI.Web.ViewModels.Articulos;

namespace UI.Web.Controllers
{
    public class ArticulosController : BaseController
    {
        private ArticulosServicios _articulosServicios;
        private RubrosServicios _rubrosServicios;
        private ConfiguracionServicios _configuracionesServicios;
        private SucursalesServicios _sucServicios;
        private StockArticuloSucursalServicios _stockArticuloSucursalServicios;
        private ConfiguracionServicios _configuracionServicios;

        // private Usuario usr;

        public ArticulosController()
        {
            _articulosServicios = new ArticulosServicios();
            _rubrosServicios = new RubrosServicios();
            _configuracionesServicios = new ConfiguracionServicios();
            _sucServicios = new SucursalesServicios();
            _stockArticuloSucursalServicios = new StockArticuloSucursalServicios();
            _configuracionServicios = new ConfiguracionServicios();

            usr = (Usuario)System.Web.HttpContext.Current.Session["UsuarioActual"];
        }

        // GET: Articulos
        public ActionResult Index(string msj)
        {
            if (!ValidarUsuario(1, 4)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Informacion = msj;

            ArticuloIndexViewModel ArticuloVM = new ArticuloIndexViewModel();
            // Traigo todos los articulos
            //var Articulos = _articulosServicios.GetAll();

            //foreach (var articulo in Articulos)
            //{
            //    ArticuloVM.Articulos.Add(articulo);
            //}

            //Traigo las sucursales
            ArticuloVM.Sucursales = _sucServicios.GetAll();

            return View(ArticuloVM);
        }

        [HttpPost]
        public ActionResult Index(ArticuloIndexViewModel vm)
        {
            if (String.IsNullOrEmpty(vm.Filtro) && vm.Filtro.Length < 4)
            {
                ViewBag.Informacion = "Debe ingresar más de 3 letras del nombre del articulo a buscar.";
                return View(vm);
            }
            // Traigo todos los articulos
            var Articulos = GetArticulosByName(vm.Filtro.ToLower().Trim());
            vm.Articulos = new List<Articulo>();
            foreach (var articulo in Articulos)
            {
                vm.Articulos.Add(articulo);
            }

            //Traigo las sucursales
            vm.Sucursales = new List<Sucursal>();
            vm.Sucursales = _sucServicios.GetAll();

            return View(vm);
        }

        public ActionResult Agregar()
        {
            if (!ValidarUsuario(1)) return RedirectToAction("ErrorPermisos", "Base");

            //LLeno el ddl de rubros
            ViewBag.Rubros = _rubrosServicios.GetAll();
            ArticuloAgregarViewModel ArticuloVM = new ArticuloAgregarViewModel();
            return View(ArticuloVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(ArticuloAgregarViewModel articuloVM)
        {
            if (ModelState.IsValid)
            {
                var StockInicial = articuloVM.StockInicial;
                var articulo = articuloVM.Mapear();

                bool bandera = _articulosServicios.Agregar(articulo, StockInicial);
                if (bandera)
                {
                    var mensaje = "El Artículo se registró correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "No se ha podido registrar el Artículo, por favor vuelva a intentarlo.";
                    ViewBag.Rubros = _rubrosServicios.GetAll();
                    return View(articuloVM);
                }
            }
            else
            {
                ViewBag.Error = "No se ha podido registrar el Artículo, por favor vuelva a intentarlo.";
                ViewBag.Rubros = _rubrosServicios.GetAll();
                return View(articuloVM);
            }
        }

        public ActionResult Eliminar(int id)
        {
            if (!ValidarUsuario(1)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Alerta = "Se eliminará el Artículo y sus correspondientes Stocks";
            ArticuloEliminarViewModel ArticuloVM = new ArticuloEliminarViewModel(_articulosServicios.GetOne(id));
            return View(ArticuloVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(ArticuloEliminarViewModel articuloVM)
        {
            if (articuloVM.Id != 0)
            {
                var bandera = _articulosServicios.Eliminar(articuloVM.Id);
                if (bandera)
                {
                    var mensaje = "El Artículo se ha eliminado correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "El Artículo no se ha eliminado, vuelva a intentarlo.";
                    ArticuloEliminarViewModel aVM = new ArticuloEliminarViewModel(_articulosServicios.GetOne(articuloVM.Id));
                    return View(aVM);
                }
            }
            else
            {
                ViewBag.Error = "El Artículo no se ha eliminado, vuelva a intentarlo.";
                ArticuloEliminarViewModel aVM = new ArticuloEliminarViewModel(_articulosServicios.GetOne(articuloVM.Id));
                return View(aVM);
            }
        }

        public ActionResult Editar(int id)
        {
            if (!ValidarUsuario(1)) return RedirectToAction("ErrorPermisos", "Base");

            //LLeno el ddl de rubros
            ViewBag.Rubros = _rubrosServicios.GetAll();
            var ArticuloVM = new ArticuloEditarViewModel(_articulosServicios.GetOne(id));

            return View(ArticuloVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ArticuloEditarViewModel articuloVM)
        {
            if (articuloVM != null && ModelState.IsValid)
            {
                //Valido que la longitud de Nombre Etiqueta sea correcta
                var LongitudNombreEtiqueta = _configuracionesServicios.GetLongitudNombreEtiqueta();
                if (articuloVM.NombreEtiqueta.Length > LongitudNombreEtiqueta)
                {
                    ViewBag.Error = "Longitud Máxima del campo Nombre Etqueta " + LongitudNombreEtiqueta + " caracteres";
                    ViewBag.Rubros = _rubrosServicios.GetAll();
                    return View("Editar", articuloVM);
                }

                var bandera = _articulosServicios.Editar(articuloVM.Mapear());
                if (bandera)
                {
                    var mensaje = "El Artículo se ha actualizado correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "El Artículo no se ha actualizado, vuelva a intentarlo.";
                    ViewBag.Rubros = _rubrosServicios.GetAll();
                    return View("Editar", articuloVM);
                }
            }
            else
            {
                ViewBag.Error = "El Artículo no se ha actualizado, vuelva a intentarlo.";
                ViewBag.Rubros = _rubrosServicios.GetAll();
                return View("Editar", articuloVM);
            }
        }

        public ActionResult BusquedaArticulo(string term)
        {
            var articulos = _articulosServicios.GetByNameOrCode(term);
            var articulo = (from obj in articulos select new { Id = obj.Id, Nombre = obj.Nombre + " (" + obj.Codigo + ")", Codigo = obj.Codigo });
            return Json(articulo, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Importar()
        {
            if (!ValidarUsuario(1, 4)) return RedirectToAction("ErrorPermisos", "Base");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Importar(HttpPostedFileBase upload)
        {
            try
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    //string filePath = Path.Combine(HttpContext.Server.MapPath("~/Uploads"), Path.GetFileName(upload.FileName));
                    string file = Path.GetFileName(upload.FileName);
                    //string path = WebConfigurationManager.AppSettings["CarpetaUpload"].ToString();
                    //string filePath = @"" + path + file;
                    string filePath = Path.Combine(System.Web.HttpContext.Current.Server.MapPath(@"~/"), file);
                    //finalFileNameWithPath = string.Format("{0}.xlsx", currentDirectorypath);

                    upload.SaveAs(filePath);
                    DataSet ds = new DataSet();

                    string ConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties=Excel 12.0;";
                    //  string ConnectionString = WebConfigurationManager.AppSettings["ExcelConn"].ToString();

                    using (OleDbConnection conn = new System.Data.OleDb.OleDbConnection(ConnectionString))
                    {
                        conn.Open();
                        using (DataTable dtExcelSchema = conn.GetSchema("Tables"))
                        {
                            string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                            string query = "SELECT * FROM [" + sheetName + "]";

UI.Web/Controllers/StockMovimientosController.cs
using System.Linq;
using System.Web.Mvc;
using Servicios;
using UI.Web.ViewModels.StockMovimientos;
using Modelos;
using System;

namespace UI.Web.Controllers
{
    public class StockMovimientosController : BaseController
    {
        private StockMovimientosServicios _stockMovimientosServicios;
        private TipoMovimientosStockServicios _tiposStockMovimientosServicios;
        private SucursalesServicios _sucursalesServicios;
        //private Usuario usr;
        //private int sucID;

        public StockMovimientosController()
        {
            _stockMovimientosServicios = new StockMovimientosServicios();
            _tiposStockMovimientosServicios = new TipoMovimientosStockServicios();
            _sucursalesServicios = new SucursalesServicios();
            sucID = (int)System.Web.HttpContext.Current.Session["SucursalActual"];
            usr = (Usuario)System.Web.HttpContext.Current.Session["UsuarioActual"];
        }

        // GET: Proveedores
        public ActionResult Index(string msj)
        {
            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Informacion = msj;

            //Traigo los movimientos de stock con los filtros correspondientes.
            CargarSucursales();
            StockMovimientoIndexViewModel StockMovimientoVM = new StockMovimientoIndexViewModel();
            StockMovimientoVM.FechaDesde = DateTime.Now;
            StockMovimientoVM.FechaHasta = DateTime.Now;
            StockMovimientoVM.SucursalID = sucID;
            StockMovimientoVM.StockMovimientos = _stockMovimientosServicios.GetAllByDate(sucID, DateTime.Now, DateTime.Now);

            return View(StockMovimientoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(StockMovimientoIndexViewModel StockMovimientoVM)
        {
            if (ModelState.IsValid)
            {
                StockMovimientoVM.StockMovimientos = _stockMovimientosServicios.GetAllByDate(
                    StockMovimientoVM.SucursalID, StockMovimientoVM.FechaDesde, StockMovimientoVM.FechaHasta);
            }
            else
            {
                ViewBag.Error = "No pudo realizarse la búsqueda, vuelva a intentarlo.";
            }
            CargarSucursales();
            return View(StockMovimientoVM);
        }

        public ActionResult Agregar()
        {

            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            var tipos = _tiposStockMovimientosServicios.GetAll();
            ViewBag.TiposMovimientosStock = tipos.ToList();
            StockMovimientoAgregarViewModel StockMovimientoVM = new StockMovimientoAgregarViewModel();
            return View(StockMovimientoVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(StockMovimientoAgregarViewModel stockMovimientoVM)
        {

            ViewBag.TiposMovimientosStock = _tiposStockMovimientosServicios.GetAll();
            if (ModelState.IsValid && stockMovimientoVM.ArticuloID != 0)
            {
                var StockMovimiento = stockMovimientoVM.Mapear();
                StockMovimiento.ArticuloID = stockMovimientoVM.ArticuloID;
                bool bandera = _stockMovimientosServicios.Agregar(StockMovimiento, sucID);
                if (bandera)
                {
                    return RedirectToAction("Index", new { msj = "El Movimiento de Stock se registró correctamente!" });
                }
                else
                {
                    ViewBag.Error = "No se ha podido registrar el Movimiento de Stock, por favor vuelva a intentarlo.";
                    return View(stockMovimientoVM);
                }
            }
            else
            {
                ViewBag.Error = "No se ha podido registrar el Movimiento de Stock, por favor vuelva a intentarlo.";
                return View(stockMovimientoVM);
            }

        }

        private void CargarSucursales()
        {
            ViewBag.Sucursales = _sucursalesServicios.GetAll();
        }
    }
}

UI.Web/Views/StockMovimientos/Agregar.cshtml
@model UI.Web.ViewModels.StockMovimientos.StockMovimientoAgregarViewModel
@{
    ViewBag.Title = "Agregar Movimiento de Stock";
}

<script>
    // AUTOCOMPLETADO ARTICULOS
    $(function () {

        $("html,body").css("overflow", "auto"); // Impide que el body modifique su tamaño al tipear en el textbox
        $("#TerminoBusquedaArticulo").autocomplete({
            // El source del autocomplete es una acción de controlador
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("BusquedaArticulo", "Articulos")',
                    type: 'GET',
                    dataType: 'json',
                    data: request,
                    success: function (data) {
                        if (!data.length) {
                            $("#ArticuloIDAgregar").val(0);
                        }
                        response($.map(data, function (item) {
                            return { label: item.Nombre, id: item.Id };
                        }));
                    },
                });
            },
            // Al seleccionar un resultado, seteamos los valores de clave y valor
            select: function (event, ui) {
                $("#TerminoBusquedaArticulo").val(ui.item.label);
                $("#ArticuloIDAgregar").val(ui.item.id);
                //alert(ui.item.id)
                return false;
            }
        }).autocomplete("widget").addClass("textbox-autocomplete");
    });

</script>

@using (Html.BeginForm("Agregar", "StockMovimientos", FormMethod.Post, new { @class = "formulario form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="container">
        <fieldset>
            <legend>Agregar Movimiento de Stock</legend>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ArticuloID, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="TerminoBusquedaArticulo" autofocus />
                            @Html.HiddenFor(model => model.ArticuloID, new { id = "ArticuloIDAgregar" })
                            @Html.ValidationMessageFor(model => model.ArticuloID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.TipoMovimientoStockID, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownListFor(model => model.TipoMovimientoStockID, new SelectList(ViewBag.TiposMovimientosStock, "Id", "Nombre"), "Seleccionar...", htmlAttributes: new { @class = "form-control", autofocus = "" })
                            @Html.HiddenFor(model => model.TipoMovimientoStockID)
                            @Html.ValidationMessageFor(model => model.TipoMovimientoStockID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

        </fieldset>

        @*Botones Aceptar y Cancelar*@
        <div class="row">
            <div class="form-group col-md-12">
                <button type="submit" class="btn btn-primary">Aceptar</button>
                <a href="@Url.Action("Index", "StockMovimientos")" class="btn btn-default">Cancelar</a>
            </div>
        </div>


    </div>
}

UI.Web/Views/StockMovimientos/Index.cshtml
@model UI.Web.ViewModels.StockMovimientos.StockMovimientoIndexViewModel
@using UI.Web.Helpers
@{
    ViewBag.Title = "Stock Movimientos";
}

@section scripts{
    <script>
        $(document).ready(function () {
            $('#stockMovimientos').DataTable({
                "sDom":
                    '<"toolbar">frtip',
                stateSave: true,
                "language":
                {
                    "url": '@Url.Content("~/Content/JSON/Spanish.json")'
                },
                "columnDefs":
                    [{
                        bSortable: false,
                        aTargets: [-1]
                    }],
                "initComplete":
                    function (settings, json) {
                        $("div.toolbar").html(
                            '<a href="@Url.Action("Agregar", "StockMovimientos")" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus"></span> Agregar</a>');
                    }
            })
        }
        );
    </script>
}

<div class="cabecera" style="margin-bottom: 20px;">
    Movimientos de Stock
</div>

@using (Html.BeginForm("Index", "StockMovimientos", FormMethod.Post, new { id = "frmStockMovimientos", @class = "formulario form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <div class="row form-inline">
        <div class="col-md-12">
            <div class="col-md-1">
                <h4>Desde:</h4>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(model => model.FechaDesde, "{0:dd/MM/yyyy}", new { @class = "form-control datetimepicker desde", @maxlength = 10 })
            </div>
            <div class="col-md-1">
                <h4>Hasta:</h4>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(model => model.FechaHasta, "{0:dd/MM/yyyy}", new { @class = "form-control datetimepicker hasta", @maxlength = 10 })
            </div>
            <div class="col-md-1">
                <h4>Sucursal:</h4>
            </div>
            <div class="col-md-2">
                @Html.DropDownListFor(model => model.SucursalID, new SelectList(ViewBag.Sucursales, "Id", "Nombre"), "Seleccionar...", htmlAttributes: new { @class = "form-control", autofocus = "" })
                @Html.HiddenFor(model => model.SucursalID)
                @Html.ValidationMessageFor(model => model.SucursalID, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
        </div>
    </div>
    <hr />
}

<div class="grilla-listados">
    <table id="stockMovimientos" class="table table-bordered table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Articulo</th>
                <th>Fecha y Hora</th>
                <th>Usuario</th>
                <th>Cantidad</th>
                <th>Stock Actual</th>
                <th>Sucursal</th>
                <th>Motivo</th>
                
                @*<th></th>*@
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.StockMovimientos)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Articulo.Codigo)</td>
                    <td>@Html.DisplayFor(modelItem => item.Articulo.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                    <td>@Html.DisplayFor(modelItem => item.Usuario.DNI)</td>
                    <td>@Html.MovimientoStock(item.Cantidad)</td>
                    <td>@Html.DisplayFor(modelItem => item.StockActual)</td>
                    <td>@Html.DisplayFor(modelItem => item.Sucursal.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Motivo.Nombre)</td>
                    

                    @*<td style="text-align:center">
                        <a href="@Url.Action("Detalles", "StockMovimientos", new { id = item.Id })" class="btn btn-primary btn-xs">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <a href="@Url.Action("Editar", "Movimientos", new { id = item.Id })" class="btn btn-primary btn-xs">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <a href="@Url.Action("Eliminar", "Movimientos", new { id = item.Id })" class="btn btn-danger btn-xs">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                    </td>*@
                </tr>
            }

        </tbody>

    </table>
</div>

<script>
    $(function () {
        $('.desde').datetimepicker({
            lang: 'es',
            i18n: {
                de: {
                    months: [
                     'Enero', 'Febrero', 'Marzo', 'Abril',
                     'Mayo', 'Junio', 'Julio', 'Agosto',
                     'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                    ],
                    dayOfWeek: [
                     "Do", "Lu", "Ma", "Mi",
                     "Ju", "Vi", "Sa",
                    ]
                }
            },
            closeOnDateSelect: true,
            timepicker: false,
            format: 'd/m/Y'
        });
        $('.hasta').datetimepicker({
            closeOnDateSelect: true,
            lang: 'es',
            i18n: {
                de: {
                    months: [
                     'Enero', 'Febrero', 'Marzo', 'Abril',
                     'Mayo', 'Junio', 'Julio', 'Agosto',
                     'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                    ],
                    dayOfWeek: [
                     "Do", "Lu", "Ma", "Mi",
                     "Ju", "Vi", "Sa",
                    ]
                }
            },
            timepicker: false,
            format: 'd/m/Y'
        });
    });
</script>