UI.Web/ViewModels/DevolucionesSinTicket/DevolucionSinTicketIndexViewModel.cs
using System;
using System.Collections.Generic;
using Modelos;
using System.ComponentModel.DataAnnotations;

namespace UI.Web.ViewModels.DevolucionesSinTicket
{
    public class DevolucionSinTicketIndexViewModel
    {
        public DevolucionSinTicketIndexViewModel()
        {
            DevolucionesSinTicket = new List<DevolucionSinTicket>();
        }

        public List<DevolucionSinTicket> DevolucionesSinTicket { get; set; }

        [Display(Name = "Fecha desde")]
        public DateTime FechaDesde { get; set; }

        [Display(Name = "Fecha hasta")]
        public DateTime FechaHasta { get; set; }
    }
}

UI.Web/Controllers/ArticulosController.cs
using BarcodeLib;
using Modelos;
using Servicios;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Web.Util;
using UI.Web.ViewModels.Articulos;

namespace UI.Web.Controllers
{
    public class ArticulosController : BaseController
    {
        private ArticulosServicios _articulosServicios;
        private RubrosServicios _rubrosServicios;
        private ConfiguracionServicios _configuracionesServicios;
        private SucursalesServicios _sucServicios;
        private StockArticuloSucursalServicios _stockArticuloSucursalServicios;
        private ConfiguracionServicios _configuracionServicios;

        // private Usuario usr;

        public ArticulosController()
        {
            _articulosServicios = new ArticulosServicios();
            _rubrosServicios = new RubrosServicios();
            _configuracionesServicios = new ConfiguracionServicios();
            _sucServicios = new SucursalesServicios();
            _stockArticuloSucursalServicios = new StockArticuloSucursalServicios();
            _configuracionServicios = new ConfiguracionServicios();

            usr = (Usuario)System.Web.HttpContext.Current.Session["UsuarioActual"];
        }

        // GET: Articulos
        public ActionResult Index(string msj)
        {
            if (!ValidarUsuario(1, 4)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Informacion = msj;

            ArticuloIndexViewModel ArticuloVM = new ArticuloIndexViewModel();
            // Traigo todos los articulos
            //var Articulos = _articulosServicios.GetAll();

            //foreach (var articulo in Articulos)
            //{
            //    ArticuloVM.Articulos.Add(articulo);
            //}

            //Traigo las sucursales
            ArticuloVM.Sucursales = _sucServicios.GetAll();

            return View(ArticuloVM);
        }

        [HttpPost]
        public ActionResult Index(ArticuloIndexViewModel vm)
        {
            if (String.IsNullOrEmpty(vm.Filtro) && vm.Filtro.Length < 4)
            {
                ViewBag.Informacion = "Debe ingresar más de 3 letras del nombre del articulo a buscar.";
                return View(vm);
            }
            // Traigo todos los articulos
            var Articulos = GetArticulosByName(vm.Filtro.ToLower().Trim());
            vm.Articulos = new List<Articulo>();
            foreach (var articulo in Articulos)
            {
                vm.Articulos.Add(articulo);
            }

            //Traigo las sucursales
            vm.Sucursales = new List<Sucursal>();
            vm.Sucursales = _sucServicios.GetAll();

            return View(vm);
        }

        public ActionResult Agregar()
        {
            if (!ValidarUsuario(1)) return RedirectToAction("ErrorPermisos", "Base");

            //LLeno el ddl de rubros
            ViewBag.Rubros = _rubrosServicios.GetAll();
            ArticuloAgregarViewModel ArticuloVM = new ArticuloAgregarViewModel();
            return View(ArticuloVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(ArticuloAgregarViewModel articuloVM)
        {
            if (ModelState.IsValid)
            {
                var StockInicial = articuloVM.StockInicial;
                var articulo = articuloVM.Mapear();

                bool bandera = _articulosServicios.Agregar(articulo, StockInicial);
                if (bandera)
                {
                    var mensaje = "El Artículo se registró correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "No se ha podido registrar el Artículo, por favor vuelva a intentarlo.";
                    ViewBag.Rubros = _rubrosServicios.GetAll();
                    return View(articuloVM);
                }
            }
            else
            {
                ViewBag.Error = "No se ha podido registrar el Artículo, por favor vuelva a intentarlo.";
                ViewBag.Rubros = _rubrosServicios.GetAll();
                return View(articuloVM);
            }
        }

        public ActionResult Eliminar(int id)
        {
            if (!ValidarUsuario(1)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Alerta = "Se eliminará el Artículo y sus correspondientes Stocks";
            ArticuloEliminarViewModel ArticuloVM = new ArticuloEliminarViewModel(_articulosServicios.GetOne(id));
            return View(ArticuloVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(ArticuloEliminarViewModel articuloVM)
        {
            if (articuloVM.Id != 0)
            {
                var bandera = _articulosServicios.Eliminar(articuloVM.Id);
                if (bandera)
                {
                    var mensaje = "El Artículo se ha eliminado correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "El Artículo no se ha eliminado, vuelva a intentarlo.";
                    ArticuloEliminarViewModel aVM = new ArticuloEliminarViewModel(_articulosServicios.GetOne(articuloVM.Id));
                    return View(aVM);
                }
            }
            else
            {
                ViewBag.Error = "El Artículo no se ha eliminado, vuelva a intentarlo.";
                ArticuloEliminarViewModel aVM = new ArticuloEliminarViewModel(_articulosServicios.GetOne(articuloVM.Id));
                return View(aVM);
            }
        }

        public ActionResult Editar(int id)
        {
            if (!ValidarUsuario(1)) return RedirectToAction("ErrorPermisos", "Base");

            //LLeno el ddl de rubros
            ViewBag.Rubros = _rubrosServicios.GetAll();
            var ArticuloVM = new ArticuloEditarViewModel(_articulosServicios.GetOne(id));

            return View(ArticuloVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ArticuloEditarViewModel articuloVM)
        {
            if (articuloVM != null && ModelState.IsValid)
            {
                //Valido que la longitud de Nombre Etiqueta sea correcta
                var LongitudNombreEtiqueta = _configuracionesServicios.GetLongitudNombreEtiqueta();
                if (articuloVM.NombreEtiqueta.Length > LongitudNombreEtiqueta)
                {
                    ViewBag.Error = "Longitud Máxima del campo Nombre Etqueta " + LongitudNombreEtiqueta + " caracteres";
                    ViewBag.Rubros = _rubrosServicios.GetAll();
                    return View("Editar", articuloVM);
                }

                var bandera = _articulosServicios.Editar(articuloVM.Mapear());
                if (bandera)
                {
                    var mensaje = "El Artículo se ha actualizado correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "El Artículo no se ha actualizado, vuelva a intentarlo.";
                    ViewBag.Rubros = _rubrosServicios.GetAll();
                    return View("Editar", articuloVM);
                }
            }
            else
            {
                ViewBag.Error = "El Artículo no se ha actualizado, vuelva a intentarlo.";
                ViewBag.Rubros = _rubrosServicios.GetAll();
                return View("Editar", articuloVM);
            }
        }

        public ActionResult BusquedaArticulo(string term)
        {
            var articulos = _articulosServicios.GetByNameOrCode(term);
            var articulo = (from obj in articulos select new { Id = obj.Id, Nombre = obj.Nombre + " (" + obj.Codigo + ")", Codigo = obj.Codigo });
            return Json(articulo, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Importar()
        {
            if (!ValidarUsuario(1, 4)) return RedirectToAction("ErrorPermisos", "Base");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Importar(HttpPostedFileBase upload)
        {
            try
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    //string filePath = Path.Combine(HttpContext.Server.MapPath("~/Uploads"), Path.GetFileName(upload.FileName));
                    string file = Path.GetFileName(upload.FileName);
                    //string path = WebConfigurationManager.AppSettings["CarpetaUpload"].ToString();
                    //string filePath = @"" + path + file;
                    string filePath = Path.Combine(System.Web.HttpContext.Current.Server.MapPath(@"~/"), file);
                    //finalFileNameWithPath = string.Format("{0}.xlsx", currentDirectorypath);

                    upload.SaveAs(filePath);
                    DataSet ds = new DataSet();

                    string ConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties=Excel 12.0;";
                    //  string ConnectionString = WebConfigurationManager.AppSettings["ExcelConn"].ToString();

                    using (OleDbConnection conn = new System.Data.OleDb.OleDbConnection(ConnectionString))
                    {
                        conn.Open();
                        using (DataTable dtExcelSchema = conn.GetSchema("Tables"))
                        {
                            string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                            string query = "SELECT * FROM [" + sheetName + "]";

UI.Web/Controllers/DevolucionesSinTicketController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UI.Web.ViewModels.DevolucionesSinTicket;
using Servicios;
using Modelos;

namespace UI.Web.Controllers
{
    public class DevolucionesSinTicketController : BaseController
    {
        DevolucionesSinTicketServicios _devolucionesSinTicketServicios;
        ArticulosServicios _articulosServicios;
        StockArticuloSucursalServicios _stockArticuloSucursalServicios;

        public DevolucionesSinTicketController()
        {
            _devolucionesSinTicketServicios = new DevolucionesSinTicketServicios();
            _articulosServicios = new ArticulosServicios();
            _stockArticuloSucursalServicios = new StockArticuloSucursalServicios();
        }

        // GET: DevolucionesSinTicket
        public ActionResult Index(string msj)
        {
           // if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Alerta = msj;

            DevolucionSinTicketIndexViewModel DevolucionSinTicketVM = new DevolucionSinTicketIndexViewModel();
            DevolucionSinTicketVM.FechaDesde = DateTime.Now;
            DevolucionSinTicketVM.FechaHasta = DateTime.Now;

            var devolucionesSinTicket = _devolucionesSinTicketServicios.GetByDate(DevolucionSinTicketVM.FechaDesde, DevolucionSinTicketVM.FechaHasta);
            var sucursalID = int.Parse(System.Web.HttpContext.Current.Session["SucursalActual"].ToString());
            DevolucionSinTicketVM.DevolucionesSinTicket = devolucionesSinTicket.Where(a => a.SucursalID == sucursalID).ToList();

            return View(DevolucionSinTicketVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(DevolucionSinTicketIndexViewModel DevolucionSinTicketVM)
        {
            if (ModelState.IsValid)
            {
                var devolucionesSinTicket = _devolucionesSinTicketServicios.GetByDate(DevolucionSinTicketVM.FechaDesde, DevolucionSinTicketVM.FechaHasta);
                var sucursalID = int.Parse(System.Web.HttpContext.Current.Session["SucursalActual"].ToString());
                DevolucionSinTicketVM.DevolucionesSinTicket = devolucionesSinTicket.Where(a => a.SucursalID == sucursalID).ToList();
            }
            else
            {
                ViewBag.Error = "No pudo realizarse la búsqueda, vuelva a intentarlo.";
            }
            return View(DevolucionSinTicketVM);
        }

        public ActionResult Agregar()
        {
            DevolucionSinTicketAgregarViewModel DevolucionSinTicketVM = new DevolucionSinTicketAgregarViewModel();
            DevolucionSinTicketVM.Cantidad = 1;

            return View(DevolucionSinTicketVM);

        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "CalcularMonto")]
        public ActionResult CalcularMonto(DevolucionSinTicketAgregarViewModel devolucionSinTicketVM)
        {
            if(devolucionSinTicketVM.ArticuloID == 0)
            {
                ViewBag.Error = "Debe seleccionar un Artículo";
                return View("Agregar", devolucionSinTicketVM);
            }

            var Articulo = _articulosServicios.GetOne(devolucionSinTicketVM.ArticuloID);
            devolucionSinTicketVM.Monto = Articulo.PrecioActualVenta * devolucionSinTicketVM.Cantidad;
            devolucionSinTicketVM.Articulo = Articulo.Nombre;
            return View("Agregar", devolucionSinTicketVM);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "AgregarDevolucionSinTicket")]
        public ActionResult AgregarDevolucionSinTicket(DevolucionSinTicketAgregarViewModel devolucionSinTicketVM)
        {
            if (devolucionSinTicketVM.ArticuloID == 0)
            {
                ViewBag.Error = "Debe seleccionar un Artículo";
                return View("Agregar", devolucionSinTicketVM);
            }
            //Vuelvo a calcular el monto, porque el usuario pudo haber cambiado los datos luego de 
            //presionar el boton "calcular monto"
            var Articulo = _articulosServicios.GetOne(devolucionSinTicketVM.ArticuloID);
            devolucionSinTicketVM.Monto = Articulo.PrecioActualVenta * devolucionSinTicketVM.Cantidad;

            var DevolucionSinTicket = devolucionSinTicketVM.Mapear();

            //Registrar la DevolucionSinTicket
            if (!_devolucionesSinTicketServicios.Add(DevolucionSinTicket))
            {
                ViewBag.Error = "No se pudo agregar la Nota de Crédito, vuelva a intentarlo";
                return View("Agregar", devolucionSinTicketVM);
            }

            //Sumar al Stock si corresponde
            if(devolucionSinTicketVM.RegresaAlStock)
            {
                int SucursalID = int.Parse(System.Web.HttpContext.Current.Session["SucursalActual"].ToString());
                var StockArticuloSucursal = _stockArticuloSucursalServicios.GetOneBySucursal(devolucionSinTicketVM.ArticuloID, SucursalID);

                StockArticuloSucursal.StockActual += devolucionSinTicketVM.Cantidad;

                _stockArticuloSucursalServicios.Update(StockArticuloSucursal);
            }

            //Registrar el monto en una variable de sesion
            System.Web.HttpContext.Current.Session["SaldoAFavor"] = devolucionSinTicketVM.Monto;

            return RedirectToAction("Agregar", "Ventas");
        }

        public ActionResult Eliminar (int id)
        {
             if(id != 0)
            {
                DevolucionSinTicket DevolucionSinTicket = _devolucionesSinTicketServicios.GetOne(id);

                //Actualizo el Stock si corresponde
                if (DevolucionSinTicket.RegresaAlStock)
                {
                    var StockArticuloSucursal = _stockArticuloSucursalServicios.GetOneBySucursal(DevolucionSinTicket.ArticuloID, DevolucionSinTicket.SucursalID);

                    StockArticuloSucursal.StockActual -= DevolucionSinTicket.Cantidad;

                    _stockArticuloSucursalServicios.Update(StockArticuloSucursal);
                }

                //Elimino
                if (_devolucionesSinTicketServicios.Delete(DevolucionSinTicket))
                {
                    return RedirectToAction("Index", new { msj = "La Nota de Crédito se eliminó correctamente." });
                }
                else
                {
                    return RedirectToAction("Index", new { msj = "No se pudo eliminar la Nota de Crédito, vuelva a intentarlo." });
                }
            }
            else
            {
                return RedirectToAction("Index", new { msj = "No se pudo eliminar la Nota de Crédito, vuelva a intentarlo." });
            }

        }

    }
}

UI.Web/Views/DevolucionesSinTicket/Agregar.cshtml
@model UI.Web.ViewModels.DevolucionesSinTicket.DevolucionSinTicketAgregarViewModel
@using UI.Web.Helpers;
@{
    ViewBag.Title = "Agregar Nota de Crédito";
}

<script>
    // AUTOCOMPLETADO ARTICULOS
    $(function () {

        $("html,body").css("overflow", "auto"); // Impide que el body modifique su tamaño al tipear en el textbox
        $("#TerminoBusquedaArticulo").autocomplete({
            // El source del autocomplete es una acción de controlador
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("BusquedaArticulo", "Articulos")',
                    type: 'GET',
                    dataType: 'json',
                    data: request,
                    success: function (data) {
                        if (!data.length) {
                            $("#ArticuloIDAgregar").val(0);
                        }
                        response($.map(data, function (item) {
                            return { label: item.Nombre, id: item.Id };
                        }));
                    },
                });
            },
            // Al seleccionar un resultado, seteamos los valores de clave y valor
            select: function (event, ui) {
                $("#TerminoBusquedaArticulo").val(ui.item.label);
                $("#ArticuloIDAgregar").val(ui.item.id);
                //alert(ui.item.id)
                return false;
            }
        }).autocomplete("widget").addClass("textbox-autocomplete");
    });

</script>

@using (Html.BeginForm("Agregar", "DevolucionesSinTicket", FormMethod.Post, new { @class = "formulario form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="container">
        <fieldset>
            <legend>Agregar Devolución / Nota de Crédito</legend>
            @if (Model.ArticuloID == 0)
            {
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ArticuloID, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="TerminoBusquedaArticulo" autofocus />
                                @Html.HiddenFor(model => model.ArticuloID, new { id = "ArticuloIDAgregar" })
                                @Html.ValidationMessageFor(model => model.ArticuloID, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            }
            else
            {
                @Html.HiddenFor(model => model.ArticuloID, new { id = "ArticuloIDAgregar" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Articulo, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Articulo, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                                @Html.ValidationMessageFor(model => model.Articulo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            }


            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <button type="submit" name="action:CalcularMonto" class="btn btn-success">
                    Calcular Monto
                    <i class="glyphicon glyphicon glyphicon-refresh"></i>
                </button>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @*@Html.TextBoxFor(model => model.Monto, new { @class = "form-control" })*@
                            @Html.DecimalFor(model => model.Monto, Model.Monto, new { @class = "form-control", @readonly = "" })
                            @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Motivo, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Motivo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Motivo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-4">
                        </div>
                        <div class="col-md-8">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.RegresaAlStock)
                                <strong>
                                    Regresa al Stock?
                                </strong>
                                @Html.ValidationMessageFor(model => model.RegresaAlStock, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </fieldset>

        @*Botones Aceptar y Cancelar*@
        <div class="row">
            <div class="form-group col-md-12">
                <button type="submit" name="action:AgregarDevolucionSinTicket" class="btn btn-primary">
                    Aceptar
                </button>
                    <a href="@Url.Action("Index", "DevolucionesSinTicket")" class="btn btn-default">Cancelar</a>
            </div>
        </div>


    </div>
}

UI.Web/Views/DevolucionesSinTicket/Index.cshtml
@model UI.Web.ViewModels.DevolucionesSinTicket.DevolucionSinTicketIndexViewModel
@{
    ViewBag.Title = "DevolucionesSinTicket";
}

<div class="cabecera" style="margin-bottom: 20px;">
    Notas de Crédito
</div>
@using (Html.BeginForm("Index", "DevolucionesSinTicket", FormMethod.Post, new { id = "form-filtro", @class = "formulario form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
    <div class="row form-inline">
        <div class="col-md-12">
            <div class="col-md-2">
                <h4>Desde:</h4>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(model => model.FechaDesde, "{0:dd/MM/yyyy}", new { @class = "form-control datetimepicker desde", @maxlength = 10 })
            </div>
            <div class="col-md-2">
                <h4>Hasta:</h4>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(model => model.FechaHasta, "{0:dd/MM/yyyy}", new { @class = "form-control datetimepicker hasta", @maxlength = 10 })
            </div>

            <div class="col-md-2">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
        </div>
    </div>
    <hr />
}

<div class="grilla-listados">
    <table id="devolucionesSinTicket" class="table table-bordered table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th>Fecha / Hora</th>
                <th>Articulo</th>
                <th>Sucursal</th>
                <th>Motivo</th>
                <th>Regresa al Stock?</th>
                <th>Cantidad</th>
                <th>Monto</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.DevolucionesSinTicket)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                    <td>@Html.DisplayFor(modelItem => item.Articulo.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Sucursal.Nombre)</td>
                    <td>@Html.DisplayFor(modelItem => item.Motivo)</td>
                    <td>@Html.DisplayFor(modelItem => item.RegresaAlStock)</td>
                    <td>@Html.DisplayFor(modelItem => item.Cantidad)</td>
                    <td>@Html.DisplayFor(modelItem => item.Monto)</td>
                    <td style="text-align:center">
                        <a href="@Url.Action("Eliminar", "DevolucionesSinTicket", new { id = item.Id })" class="btn btn-danger btn-xs" onclick="OpenSweetAlert()">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#devolucionesSinTicket').DataTable({
                "sDom":
                    '<"toolbar">frtip',
                stateSave: true,
                "language":
                {
                    "url": '@Url.Content("~/Content/JSON/Spanish.json")'
                },
                "columnDefs":
                    [{
                        bSortable: false,
                        aTargets: [-1]
                    }],
                "initComplete":
                    function (settings, json) {
                        $("div.toolbar").html(
                            '<a href="@Url.Action("Agregar", "DevolucionesSinTicket")" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus"></span> Agregar</a>');
                    }
            })
        }
        );

        $(function () {
            $('.desde').datetimepicker({
                lang: 'es',
                i18n: {
                    de: {
                        months: [
                         'Enero', 'Febrero', 'Marzo', 'Abril',
                         'Mayo', 'Junio', 'Julio', 'Agosto',
                         'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                        ],
                        dayOfWeek: [
                         "Do", "Lu", "Ma", "Mi",
                         "Ju", "Vi", "Sa",
                        ]
                    }
                },
                closeOnDateSelect: true,
                timepicker: false,
                format: 'd/m/Y'
            });
            $('.hasta').datetimepicker({
                closeOnDateSelect: true,
                lang: 'es',
                i18n: {
                    de: {
                        months: [
                         'Enero', 'Febrero', 'Marzo', 'Abril',
                         'Mayo', 'Junio', 'Julio', 'Agosto',
                         'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
                        ],
                        dayOfWeek: [
                         "Do", "Lu", "Ma", "Mi",
                         "Ju", "Vi", "Sa",
                        ]
                    }
                },
                timepicker: false,
                format: 'd/m/Y'
            });
        });
    </script>
}