UI.Web/Controllers/RubrosController.cs
using System.Web.Mvc;
using Modelos;
using UI.Web.ViewModels.Rubros;
using Servicios;

namespace UI.Web.Controllers
{
    public class RubrosController : BaseController
    {
        private RubrosServicios _rubrosServicios;
       // private Usuario usr;

        public RubrosController()
        {
            _rubrosServicios = new RubrosServicios();
            usr = (Usuario)System.Web.HttpContext.Current.Session["UsuarioActual"];
        }

        // GET: Rubros
        public ActionResult Index(string msj)
        {
            if (!ValidarUsuario(1,2)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Informacion = msj;

            var Rubros = _rubrosServicios.GetAll();
            RubroIndexViewModel RubroVM = new RubroIndexViewModel();
            foreach (var rubro in Rubros)
            {
                RubroVM.Rubros.Add(rubro);
            }
            return View(RubroVM);
        }

        public ActionResult Agregar()
        {
            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            RubroAgregarViewModel RubroVM = new RubroAgregarViewModel();
            return View(RubroVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(RubroAgregarViewModel rubroVM)
        {
            if (ModelState.IsValid)
            {
                bool bandera = _rubrosServicios.Add(rubroVM.Mapear());
                if (bandera)
                {
                    return RedirectToAction("Index", new { msj = "El Rubro se registró correctamente!" });
                }
                else
                {
                    ViewBag.Error = "No se ha podido registrar el Rubro, por favor vuelva a intentarlo.";
                    return View(rubroVM);
                }
            }
            else
            {
                ViewBag.Error = "No se ha podido registrar el Rubro, por favor vuelva a intentarlo.";
                return View(rubroVM);
            }
        }

        public ActionResult Eliminar(int id)
        {
            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            ViewBag.Alerta = "Se eliminará el Rubro";
            var RubroVM = new RubroEliminarViewModel(_rubrosServicios.GetOne(id));
            return View(RubroVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(RubroEliminarViewModel rubroVM)
        {
            if (rubroVM.Id != 0)
            {
                var Rubro = _rubrosServicios.GetOne(rubroVM.Id);
                Rubro.Habilitado = false;
                var bandera = _rubrosServicios.Update(Rubro);
                if (bandera)
                {
                    var mensaje = "El Rubro se ha eliminado correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "El Rubro no se ha eliminado, vuelva a intentarlo.";
                    RubroEliminarViewModel RubroVM = new RubroEliminarViewModel(_rubrosServicios.GetOne(rubroVM.Id));
                    return View(RubroVM);
                }

            }
            else
            {
                ViewBag.Error = "El Rubro no se ha eliminado, vuelva a intentarlo.";
                RubroEliminarViewModel RubroVM = new RubroEliminarViewModel(_rubrosServicios.GetOne(rubroVM.Id));
                return View(RubroVM);
            }
        }

        public ActionResult Editar(int id)
        {
            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            var RubroVM = new RubroEditarViewModel(_rubrosServicios.GetOne(id));

            return View(RubroVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(RubroEditarViewModel rubroVM)
        {
            if (rubroVM != null)
            {
                var bandera = _rubrosServicios.Update(rubroVM.Mapear());
                if (bandera)
                {
                    return RedirectToAction("Index", new { msj = "El Rubro se ha actualizado correctamente!" });
                }
                else
                {
                    ViewBag.Error = "El Rubro no se ha actualizado, vuelva a intentarlo.";
                    return View(rubroVM);
                }
            }
            else
            {
                ViewBag.Error = "El Rubro no se ha actualizado, vuelva a intentarlo.";
                return View(rubroVM);
            }
        }

    }
}

UI.Web/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Modelos;
using UI.Web.ViewModels.Stock;
using Servicios;

namespace UI.Web.Controllers
{
    public class StockController : BaseController
    {
        private ArticulosServicios _articulosServicios;
        private SucursalesServicios _sucursalesServicios;
        private StockArticuloSucursalServicios _stockArticuloSucursalServicios;
        private StockMovimientosServicios _stockMovimientosServicios;
        private TipoMovimientosStockServicios _tipoMovimientosStockServicios;

        public StockController()
        {
            _articulosServicios = new ArticulosServicios();
            _sucursalesServicios = new SucursalesServicios();
            _stockArticuloSucursalServicios = new StockArticuloSucursalServicios();
            _stockMovimientosServicios = new StockMovimientosServicios();
            _tipoMovimientosStockServicios = new TipoMovimientosStockServicios();


        }

        // GET: Stock
        public ActionResult Index(string msj)
        {
            ViewBag.Informacion = msj;

            StockIndexViewModel StockVM = new StockIndexViewModel();

            //Articulos
            var Articulos = _articulosServicios.GetAll();
            foreach (var articulo in Articulos)
            {
                StockVM.Articulos.Add(articulo);
                StockVM.TotalesStock.Add(articulo.Stock.Sum(a => a.StockActual));
            }

            //Sucursales
            var Sucursales = _sucursalesServicios.GetAll();
            foreach (var sucursal in Sucursales)
            {
                StockVM.Sucursales.Add(sucursal);
            }

            //Por defecto sólo muestra las alertas de stock
            StockVM.MostrarSoloAlertas = false;

            return View(StockVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(StockIndexViewModel StockVM)
        {
            //Articulos
            var Articulos = _articulosServicios.GetAll();
            foreach (var articulo in Articulos)
            {
                StockVM.Articulos.Add(articulo);
                StockVM.TotalesStock.Add(articulo.Stock.Sum(a => a.StockActual));
            }

            //Sucursales
            var Sucursales = _sucursalesServicios.GetAll();
            foreach (var sucursal in Sucursales)
            {
                StockVM.Sucursales.Add(sucursal);
            }

            return View(StockVM);
        }

        public ActionResult AsignarStock(AsignarStockViewModel AsignarVM, string mensaje)
        {
            if (!ValidarUsuario(1,2,4)) return RedirectToAction("ErrorPermisos", "Base");

            if (AsignarVM == null)
            {
                AsignarVM = new AsignarStockViewModel();            
            }

            if (mensaje != "" && mensaje != null)
            {
                ViewBag.Informacion = mensaje;
            }

            AsignarVM.Sucursales = _sucursalesServicios.GetAll();

            Session["listaStock"] = null;
           
            return View(AsignarVM);
        }

        //[HttpPost]
        //[MultipleButton(Name = "action", Argument = "AgregarArticulo")]
        //public ActionResult AgregarArticulo(AsignarStockViewModel aVM, List<LineaAsignarStockViewModel> lista)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        //VentasAgregarViewModel aVM = new VentasAgregarViewModel();
        //        if (aVM.ArticuloID == 0)
        //        {
        //            var items = System.Web.HttpContext.Current.Session["ListaItemsStock"];
        //            aVM.ListaArticulosAsignarStock = (List<LineaAsignarStockViewModel>)items;
        //            if (aVM.ListaArticulosAsignarStock.Count < 1)
        //            {
        //                ViewBag.Error = "No pudo agregarse el artículo, vuelva a intentarlo.";
        //            }
        //        }
        //        else
        //        {

        //            //var items = System.Web.HttpContext.Current.Session["ListaItemsStock"];
        //            //aVM.ListaArticulosAsignarStock = (List<LineaAsignarStockViewModel>)items;

        //            LineaAsignarStockViewModel item = new LineaAsignarStockViewModel();
        //            item.Articulo = _articulosServicios.GetOne(aVM.ArticuloID);
        //            item.ArticuloID = item.Articulo.Id;
        //            item.StockArticuloSucursal = MapearStockArticuloSucursales(item.Articulo);
        //            aVM.ListaArticulosAsignarStock.Add(item);
        //        }

        //    }
        //    else
        //    {
        //        ViewBag.Error = "No pudo agregarse el artículo, vuelva a intentarlo.";
        //    }
        //    aVM.Sucursales = _sucursalesServicios.GetAll();
        //    return View("AsignarStock", aVM);
        //}

        [HttpPost]
        public ActionResult AgregarArticulo(int? articuloID, AsignarStockViewModel AsignarVM, string articulo)
        {
            ViewBag.Sucursales = _sucursalesServicios.GetAll();
            if (AsignarVM == null)
            {
                AsignarVM = new AsignarStockViewModel();
            }
           
            if (ModelState.IsValid)
            {
                int artID = 0;
                if (articuloID == 0)
                {
                    try
                    {
                        if (articulo != "" && articulo != null)
                        {
                            artID = _articulosServicios.GetByNameOrCode(articulo).First().Id;
                        }
                        else
                        {
                            artID = int.Parse(articuloID.ToString());
                        }
                    }
                    catch (Exception ex)
                    {

                    }

                }
                else
                {
                    artID = int.Parse(articuloID.ToString());
                }

                

                if (artID == 0)
                {
                    ViewBag.Error = "No pudo agregarse el artículo, vuelva a intentarlo.";
                }
                else
                {
                    var lista = new List<LineaAsignarStockViewModel>();
                    try
                    {
                        List<LineaAsignarStockViewModel> items = (List<LineaAsignarStockViewModel>)Session["listaStock"];
                        lista.AddRange(items);
                    }
                    catch { List<LineaAsignarStockViewModel> items = new List<LineaAsignarStockViewModel>(); }
                    if (lista.Any(a => a.ArticuloID == artID))
                    {
                        ViewBag.Error = "El artículo ya se encuentra en la lista.";
                        AsignarVM.ListaArticulosAsignarStock = lista;
                    }
                    else
                    {
                        LineaAsignarStockViewModel item = new LineaAsignarStockViewModel();                  
                       

                        item.Articulo = _articulosServicios.GetOne(artID);
                        item.ArticuloID = item.Articulo.Id;
                        item.StockArticuloSucursal = MapearStockArticuloSucursales(item.Articulo);
                        lista.Add(item);
                        AsignarVM.ListaArticulosAsignarStock = lista;
                        Session["listaStock"] = lista;
                    }                    
                }

            }
            else
            {
                ViewBag.Error = "No pudo agregarse el artículo, vuelva a intentarlo.";
            }

            return PartialView("_listaArticulosStock", AsignarVM.ListaArticulosAsignarStock);          
        }
       
        public ActionResult EliminarArticulo(int articuloID, List<LineaAsignarStockViewModel> lista)
        {
            ViewBag.Sucursales = _sucursalesServicios.GetAll();
            if (lista == null)
            {
                lista = new List<LineaAsignarStockViewModel>();
            }

            if (ModelState.IsValid)
            {
                if (articuloID == 0)
                {
                    ViewBag.Error = "No pudo eliminarse el artículo, vuelva a intentarlo.";
                }
                else
                {
                    try
                    {
                        List<LineaAsignarStockViewModel> items = (List<LineaAsignarStockViewModel>)Session["listaStock"];
                        lista.AddRange(items);
                    }
                    catch { List<LineaAsignarStockViewModel> items = new List<LineaAsignarStockViewModel>(); }
                    if (lista.Any(a => a.ArticuloID == articuloID))
                    {
                        var index = lista.Where(a => a.ArticuloID == articuloID).First();
                        lista.Remove(index);
                        Session["listaStock"] = lista;
                    }
                    else
                    {
                        ViewBag.Informacion = "El artículo se ha eliminado correctamente de la lista.";
                    }
                }

            }
            else
            {
                ViewBag.Error = "No pudo eliminarse el artículo, vuelva a intentarlo.";
            }

            return PartialView("_listaArticulosStock", lista);
        }

        private List<StockArticuloSucursalViewModel> MapearStockArticuloSucursales(Articulo art)
        {
            var sucursales = _sucursalesServicios.GetAll();
            List<StockArticuloSucursalViewModel> listaVM = new List<StockArticuloSucursalViewModel>();
            foreach (var suc in sucursales)
            {
                StockArticuloSucursalViewModel sVM = new StockArticuloSucursalViewModel();
                sVM.ArticuloID = art.Id;
                sVM.Articulo = art;
                sVM.Sucursal = suc;

UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head class="bgHead">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="~/Content/Images/volante.png" />
    <title>@ViewBag.Title | Pallo Design</title>

   
    @Scripts.Render("~/Scripts/jquery")
    @Scripts.Render("~/Scripts/jqueryui")
    @Scripts.Render("~/Scripts/bootstrap")
    @Scripts.Render("~/Scripts/jqueryval")
    @Scripts.Render("~/Scripts/jqueryform")
    @Scripts.Render("~/Scripts/dt")
    @Scripts.Render("~/Scripts/jquerydatetimepicker")

    @Styles.Render("~/Content/reset")
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/Custom/customcss")
    @Styles.Render("~/Content/jqueryui/themes/base/css")
    @Styles.Render("~/Content/datetimepicker")    
    @Styles.Render("~/Content/dt")
    @Scripts.Render("~/Scripts/modernizr")
    @Scripts.Render("~/Scripts/momentjs")   

    @Styles.Render("~/Content/swal")
    @Scripts.Render("~/Scripts/swal")

</head>
<body>
    <div>
        @{ Html.RenderPartial("_Menu");  }

        @{ Html.RenderPartial("_Mensajes"); }

        <div class="contenido">
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-10">
                    @RenderBody()
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
        
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

UI.Web/Views/Shared/_LayoutOLD.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

UI.Web/Views/Shared/_LayoutVacio.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pallo Design</title>
    <link rel="shortcut icon" href="~/Content/Images/volante.png" />

    @RenderSection("AdditionalMeta", false)
</head>
<body style="background-color:#FFF; ">
    @RenderBody()

    @RenderSection("Scripts", false)
</body>
</html>

UI.Web/Views/Shared/_Menu.cshtml
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Agregar", "Ventas")">
                @*<img src="~/Content/Images/pallodesign_logo.png" height="50" alt="" />*@
                Pallo Design
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            @{
                string RolActual = System.Web.HttpContext.Current.Session["RolActual"].ToString();
                if (RolActual == "administrador")
                {
                    <ul class="nav navbar-nav" id="barraMenu">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ventas<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Agregar", "Ventas")">Nueva Venta</a></li>
                                <li><a href="@Url.Action("Index", "Ventas")">Lista Ventas</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Agregar", "Devoluciones")">Devolución</a></li>
                                <li><a href="@Url.Action("Index", "DevolucionesSinTicket")">Nota de Crédito</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Index", "Stock")">Stock</a></li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Caja<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "CierreCaja")">Cierres de Caja</a></li>
                                <li><a href="@Url.Action("Index", "Cheques")">Cheques</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "MovimientosEfectivo")">Movimiento Efectivo</a></li>
                                <li><a href="@Url.Action("Index", "TiposMovimientosEfectivo")">Tipos  de Movimiento Efectivo</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "Sueldos")">Liquidación de Sueldo</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "Articulos")">Articulos</a></li>
                                <li><a href="@Url.Action("Index", "Rubros")">Rubros</a></li>
                                <li><a href="@Url.Action("Importar", "Articulos")">Importar Articulos desde Excel</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "Clientes")">Clientes</a></li>
                                <li><a href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                                @*<li><a href="@Url.Action("Index", "Sucursales")">Sucursales</a></li>*@
                                <li><a href="@Url.Action("Index", "Usuarios")">Usuarios</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("CambiarClave", "Usuarios")">Cambiar Contraseña</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reportes<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Reporte", "Articulos")"> Artículos </a></li>
                                <li><a href="@Url.Action("ReportePorVendedor", "Ventas")"> Ventas x Vendedor </a></li>
                                <li><a href="@Url.Action("ReporteGastosGenerales", "CierreCaja")"> Total Gastos </a></li>
                                <li><a href="@Url.Action("ReporteGanancias", "CierreCaja")"> Ganancias </a></li>
                                <li><a href="@Url.Action("ReportePorRubro", "Ventas")"> Ventas x Rubro </a></li>
                            </ul>
                        </li>

                    </ul>
                }


                else if (RolActual == "adm. de stock")
                {
                    <ul class="nav navbar-nav" id="barraMenu">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ventas<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Agregar", "Ventas")">Nueva Venta</a></li>
                                @*<li><a href="@Url.Action("Index", "Ventas")">Lista Ventas</a></li>*@
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Agregar", "Devoluciones")">Devolución</a></li>
                                <li><a href="@Url.Action("Index", "DevolucionesSinTicket")">Nota de Crédito</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Index", "Stock")">Stock</a></li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Caja<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "CierreCaja")">Cierres de Caja</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "MovimientosEfectivo")">Movimiento Efectivo</a></li>
                                <li><a href="@Url.Action("Index", "TiposMovimientosEfectivo")">Tipos  de Movimiento Efectivo</a></li>
                                <li role="separator" class="divider"></li>
                                @*<li><a href="@Url.Action("Index", "Sueldos")">Liquidación de Sueldo</a></li>*@
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "Articulos")">Articulos</a></li>
                                <li><a href="@Url.Action("Index", "Rubros")">Rubros</a></li>
                                <li><a href="@Url.Action("Importar", "Articulos")">Importar Articulos desde Excel</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "Clientes")">Clientes</a></li>
                                <li><a href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("CambiarClave", "Usuarios")">Cambiar Contraseña</a></li>
                            </ul>
                        </li>
                    </ul>
                }

                else if (RolActual == "responsable")
                {
                    <ul class="nav navbar-nav" id="barraMenu">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ventas<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Agregar", "Ventas")">Nueva Venta</a></li>
                                @*<li><a href="@Url.Action("Index", "Ventas")">Lista Ventas</a></li>*@
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Agregar", "Devoluciones")">Devolución</a></li>
                                <li><a href="@Url.Action("Index", "DevolucionesSinTicket")">Nota de Crédito</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Index", "Stock")">Stock</a></li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Caja<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "CierreCaja")">Cierres de Caja</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "Sueldos")">Liquidación de Sueldo</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @*<li><a href="@Url.Action("Index", "Articulos")">Articulos</a></li>*@
                                <li><a href="@Url.Action("Index", "Rubros")">Rubros</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Index", "Clientes")">Clientes</a></li>
                                <li><a href="@Url.Action("Index", "Proveedores")">Proveedores</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("CambiarClave", "Usuarios")">Cambiar Contraseña</a></li>
                            </ul>
                        </li>
                    </ul>

                }
                else // Vendedor
                {
                    <ul class="nav navbar-nav" id="barraMenu">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ventas<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Agregar", "Ventas")">Nueva Venta</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Agregar", "Devoluciones")">Devolución</a></li>
                                <li><a href="@Url.Action("Index", "DevolucionesSinTicket")">Nota de Crédito</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Index", "Stock")">Stock</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Caja<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "CierreCaja")">Cierres de Caja</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Agregar", "MovimientosEfectivo")">Nuevo Movimiento Efectivo</a></li>
                                @*<li role="separator" class="divider"></li>
                                    <li><a href="@Url.Action("Index", "Sueldos")">Liquidación de Sueldo</a></li>*@
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "Clientes")">Clientes</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("CambiarClave", "Usuarios")">Cambiar Contraseña</a></li>
                            </ul>
                        </li>
                    </ul>
                }

            }

            <ul class="nav navbar-nav navbar-right">
                <li><a href="@Url.Action("SeleccionarSucursal", "Home")">Cambiar Sucursal</a></li>
                <li><a href="@Url.Action("Logout", "Account")">Cerrar Sesión</a></li>
            </ul>
            <p class="navbar-text navbar-right">Usr: @System.Web.HttpContext.Current.Session["DatosUsuario"] @System.Web.HttpContext.Current.Session["DatosSucursalActual"]</p>
        </div>
    </div>
</nav>