UI.Web/ViewModels/Ventas/ReportePorRubroDetalleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UI.Web.ViewModels.Ventas
{
    public class ReportePorRubroDetalleViewModel
    {
        public string Nombre { get; set; }
        public decimal Cantidad { get; set; }

        public decimal Total { get; set; }

        public string Porcentaje
        {
            get
            {
                decimal current = Cantidad;
                decimal maximum = Total;
                var percent = ((decimal)(current) / maximum);
                return percent.ToString("0.0%");
            }
        }
    }
}

UI.Web/ViewModels/Ventas/ReportePorRubroViewModel.cs
using Modelos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UI.Web.ViewModels.Ventas
{
    public class ReportePorRubroViewModel
    {
        [Display(Name = "Fecha desde")]
        public DateTime FechaDesde { get; set; }

        [Display(Name = "Fecha hasta")]
        public DateTime FechaHasta { get; set; }        

        public List<ReportePorRubroDetalleViewModel> Detalles { get; set; }

        public string CabeceraReporte { get; set; }
    }
}

UI.Web/ViewModels/Ventas/ReportePorVendedorViewModel.cs
using Modelos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace UI.Web.ViewModels.Ventas
{
    public class ReportePorVendedorViewModel
    {
        [Display(Name = "Fecha desde")]
        public DateTime FechaDesde { get; set; }

        [Display(Name = "Fecha hasta")]
        public DateTime FechaHasta { get; set; }

        public List<Venta> Ventas { get; set; }

        [Display(Name = "Vendedor")]
        public int VendedorID { get; set; }    

        public string CabeceraReporte { get; set; }

        public decimal Total
        {
            get
            {
                try { return Ventas.Sum(a => a.TotalVenta); }
                catch { return 0; }

            }
        }
    }
}

UI.Web/Controllers/ClientesController.cs
using System.Web.Mvc;
using Modelos;
using Servicios;
using System.Linq;
using UI.Web.ViewModels.Clientes;

namespace UI.Web.Controllers
{
    public class ClientesController : BaseController
    {
        private ClientesServicios _clientesServicios;
      //  private Usuario usr;

        public ClientesController()
        {
            _clientesServicios = new ClientesServicios();
            usr = (Usuario)System.Web.HttpContext.Current.Session["UsuarioActual"];
        }

        // GET: Clientes
        public ActionResult Index(string msj)
        {
            //if (usr == null) return RedirectToAction("Login", "Account");

            ViewBag.Informacion = msj;

            //Traigo todos los clientes
            var Clientes = _clientesServicios.GetAllHabilitados();
            ClienteIndexViewModel ClienteVM = new ClienteIndexViewModel();
            foreach (var cliente in Clientes)
            {
                ClienteVM.Clientes.Add(cliente);
            }
            return View(ClienteVM);
        }

        public ActionResult Agregar()
        {
            //if (usr == null) return RedirectToAction("Login", "Account");

            ClienteAgregarViewModel ClienteVM = new ClienteAgregarViewModel();
            return View(ClienteVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(ClienteAgregarViewModel clienteVM)
        {
            if (ModelState.IsValid)
            {
                var cliente = clienteVM.Mapear();

                bool bandera = _clientesServicios.Add(cliente);
                if (bandera)
                {
                    var mensaje = "El Cliente se registró correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "No se ha podido registrar el Cliente, por favor vuelva a intentarlo.";
                    return View(clienteVM);
                }
            }
            else
            {
                ViewBag.Error = "No se ha podido registrar el Cliente, por favor vuelva a intentarlo.";
                return View(clienteVM);
            }

        }

        public ActionResult Eliminar(int id)
        {
            //if (usr == null) return RedirectToAction("Login", "Account");

            ViewBag.Alerta = "Se eliminará el Cliente";
            ClienteEliminarViewModel clienteVM = new ClienteEliminarViewModel(_clientesServicios.GetOne(id));
            return View(clienteVM);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(ClienteEliminarViewModel clienteVM)
        {
            if (clienteVM.Id != 0)
            {
                var bandera = _clientesServicios.Delete(_clientesServicios.GetOne(clienteVM.Id));
                if (bandera)
                {
                    var mensaje = "El Cliente se ha eliminado correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "El Cliente no se ha eliminado, vuelva a intentarlo.";
                    ClienteEliminarViewModel cVM = new ClienteEliminarViewModel(_clientesServicios.GetOne(clienteVM.Id));
                    return View(cVM);
                }

            }
            else
            {
                ViewBag.Error = "El Cliente no se ha eliminado, vuelva a intentarlo.";
                ClienteEliminarViewModel cVM = new ClienteEliminarViewModel(_clientesServicios.GetOne(clienteVM.Id));
                return View(cVM);
            }
        }

        public ActionResult Editar(int id)
        {
            //if (usr == null) return RedirectToAction("Login", "Account");

            var ClienteVM = new ClienteEditarViewModel(_clientesServicios.GetOne(id));

            return View(ClienteVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ClienteEditarViewModel clienteVM)
        {
            if (clienteVM != null)
            {
                var bandera = _clientesServicios.Update(clienteVM.Mapear());
                if (bandera)
                {
                    var mensaje = "El Cliente se ha actualizado correctamente!";
                    return RedirectToAction("Index", new { msj = mensaje });
                }
                else
                {
                    ViewBag.Error = "El Cliente no se ha actualizado, vuelva a intentarlo.";
                    return View("Editar", clienteVM);
                }
            }
            else
            {
                ViewBag.Error = "El Cliente no se ha actualizado, vuelva a intentarlo.";
                return View("Editar", clienteVM);
            }
        }

        public ActionResult Detalles(int id)
        {
            //if (usr == null) return RedirectToAction("Login", "Account");

            ClienteDetallesViewModel ClienteVM = new ClienteDetallesViewModel(_clientesServicios.GetOne(id));
            return View(ClienteVM);

        }

        public ActionResult BusquedaClientes(string term)
        {
            var clientes = _clientesServicios.GetByNameOrDNI(term);
            var cliente = (from obj in clientes select new { Id = obj.Id, Nombre = obj.NombreCompleto + " ("+obj.DNI+")" });
            return Json(cliente, JsonRequestBehavior.AllowGet);
        }
    }
}

UI.Web/Controllers/VentasController.cs
using Modelos;
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using UI.Web.ViewModels.Ventas;

namespace UI.Web.Controllers
{
    public class VentasController : BaseController
    {
        private VentasServicios _ventasServicios;
        private VentaItemsServicios _ventaItemsServicios;
        private ArticulosServicios _articulosServicios;
        private FormasDePagoServicios _formasDePagoServicios;
        private StockArticuloSucursalServicios _stockArticuloSucursalServicios;
        private StockMovimientosServicios _stockMovimientosServicios;
        private UsuariosRolesServicios _usuariosRolesServicios;
        private PagosServicios _pagosServicios;
        //private Usuario usr;
        //private int sucID;

        public VentasController()
        {
            _ventasServicios = new VentasServicios();
            _ventaItemsServicios = new VentaItemsServicios();
            _articulosServicios = new ArticulosServicios();
            _formasDePagoServicios = new FormasDePagoServicios();
            _stockArticuloSucursalServicios = new StockArticuloSucursalServicios();
            _stockMovimientosServicios = new StockMovimientosServicios();
            _usuariosRolesServicios = new UsuariosRolesServicios();
            _pagosServicios = new PagosServicios();
            usr = (Usuario)System.Web.HttpContext.Current.Session["UsuarioActual"];
            sucID = 2;// (int)System.Web.HttpContext.Current.Session["SucursalActual"];
        }

        public ActionResult ReportePorRubro()
        {
            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            ReportePorRubroViewModel vVM = new ReportePorRubroViewModel();
            vVM.FechaDesde = DateTime.Now;
            vVM.FechaHasta = DateTime.Now;
            var ventas = _ventasServicios.GetByDate(vVM.FechaDesde, vVM.FechaHasta);
            vVM.Detalles = ArmarDetalleReportePorRubro(ventas);
            vVM.CabeceraReporte = String.Format("Reporte por Rubro de {0} a {1}", vVM.FechaDesde.ToShortDateString(), vVM.FechaHasta.ToShortDateString());
            return View(vVM);
        }

        private List<ReportePorRubroDetalleViewModel> ArmarDetalleReportePorRubro(List<Venta> ventas)
        {
            List<ReportePorRubroDetalleViewModel> detalles = new List<ReportePorRubroDetalleViewModel>();
            List<VentaItem> items = new List<VentaItem>();
            foreach (var v in ventas)
            {
                items.AddRange(v.VentaItem);
            }

            foreach (var i in items.GroupBy(a => a.Articulo.Rubro.Nombre))
            {
                ReportePorRubroDetalleViewModel vm = new ReportePorRubroDetalleViewModel();
                vm.Nombre = i.Key;
                vm.Cantidad = i.Sum(a => a.Cantidad);
                vm.Total = items.Sum(a => a.Cantidad);

                detalles.Add(vm);
            }

            return detalles;
        }

        [HttpPost]
        public ActionResult ReportePorRubro(ReportePorRubroViewModel vVM)
        {
            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            var ventas = _ventasServicios.GetByDate(vVM.FechaDesde, vVM.FechaHasta);
            vVM.Detalles = ArmarDetalleReportePorRubro(ventas);
            vVM.CabeceraReporte = String.Format("Reporte por Rubro de {0} a {1}", vVM.FechaDesde.ToShortDateString(), vVM.FechaHasta.ToShortDateString());
            return View(vVM);
        }

        private List<VentaItem> ArmarReportePorRubro(List<Venta> ventas)
        {
            List<VentaItem> items = new List<VentaItem>();
            foreach (var v in ventas)
            {
                items.AddRange(v.VentaItem);
            }
            return items;
        }

        public ActionResult ReportePorVendedor()
        {
            if (!ValidarUsuario(1, 2)) return RedirectToAction("ErrorPermisos", "Base");

            ReportePorVendedorViewModel vVM = new ReportePorVendedorViewModel();
            vVM.FechaDesde = DateTime.Now;
            vVM.FechaHasta = DateTime.Now;
            var ventas = _ventasServicios.GetByDate(vVM.FechaDesde, vVM.FechaHasta);
            vVM.Ventas = ventas.Where(a => a.SucursalID == sucID).ToList();
            ViewBag.Vendedores = _usuariosRolesServicios.GetUsuariosByRolYSucursal(sucID, 3); //El 3 es Vendedor

            return View(vVM);
        }

        [HttpPost]
        public ActionResult ReportePorVendedor(ReportePorVendedorViewModel rVM)
        {
            var ventas = _ventasServicios.GetByDate(rVM.FechaDesde, rVM.FechaHasta);
            rVM.Ventas = ventas.Where(a => a.SucursalID == sucID && a.Vendedor.Id == rVM.VendedorID).ToList();
            ViewBag.Vendedores = _usuariosRolesServicios.GetUsuariosByRolYSucursal(sucID, 3); //El 3 es Vendedor

            return View(rVM);
        }

        [HttpPost]
        public ActionResult ReportePorVendedorPrint(ReportePorVendedorViewModel rVM)
        {
            var ventas = _ventasServicios.GetByDate(rVM.FechaDesde, rVM.FechaHasta);
            rVM.Ventas = ventas.Where(a => a.SucursalID == sucID && a.Vendedor.Id == rVM.VendedorID).ToList();
            var v = _usuariosRolesServicios.GetUsuariosByRolYSucursal(sucID, 3); //El 3 es Vendedor
            var u = v.Where(a => a.Id == rVM.VendedorID).FirstOrDefault();
            rVM.CabeceraReporte = u.NombreCompleto + " (Desde: " + rVM.FechaDesde.ToShortDateString() + " Hasta: " + rVM.FechaHasta.ToShortDateString() + ")";

            return View(rVM);
        }


        // GET: Ventas
        public ActionResult Index()
        {
            if (!ValidarUsuario(1)) return RedirectToAction("ErrorPermisos", "Base");

            VentasIndexViewModel vVM = new VentasIndexViewModel();
            vVM.FechaDesde = DateTime.Today;
            vVM.FechaHasta = DateTime.Today;
            //var ventas = _ventasServicios.GetByDate(vVM.FechaDesde, vVM.FechaHasta);
            var ventas = _ventasServicios.GetAll().OrderByDescending(a => a.FechaVenta);
            vVM.Ventas = ventas.Where(a => a.SucursalID == sucID && a.Anulado == false).ToList();
            return View(vVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(VentasIndexViewModel vVM)
        {
            if (ModelState.IsValid)
            {
                var ventas = _ventasServicios.GetByDate(vVM.FechaDesde, vVM.FechaHasta);
                vVM.Ventas = ventas.Where(a => a.SucursalID == sucID && a.Anulado == false).ToList();
            }
            else
            {
                ViewBag.Error = "No pudo realizarse la búsqueda, vuelva a intentarlo.";
            }
            return View(vVM);
        }

        public ActionResult Agregar(VentasAgregarViewModel aVM, string mensaje)
        {
            //Valido que no se pueda realizar una venta cuando la sucursal es "Depósito"
            sucID = (int)System.Web.HttpContext.Current.Session["SucursalActual"];
            if (sucID == 1) return RedirectToAction("ErrorPermisoNuevaVenta", "Base");

            if (aVM == null)
            {
                aVM = new VentasAgregarViewModel();
            }

            if (mensaje != "" && mensaje != null)
            {
                ViewBag.Informacion = mensaje;
            }
            if (System.Web.HttpContext.Current.Session["SaldoAFavor"] != null)
            {
                aVM.SaldoAFavor = decimal.Parse(System.Web.HttpContext.Current.Session["SaldoAFavor"].ToString());
            }

            return View(aVM);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "AgregarPago")]
        public ActionResult AgregarPago(VentasAgregarPagoViewModel apVM)
        {
            apVM.FormasDePago = null;
            apVM.FormasDePago = new SelectList(_formasDePagoServicios.GetAll(), "Id", "Nombre", 1);
            if (apVM.FormaDePagoID != 0)
            {
                apVM.Items = (List<VentaItem>)System.Web.HttpContext.Current.Session["ListaItemsVentaActual"];
                var formaDePago = _formasDePagoServicios.GetOne(apVM.FormaDePagoID);
                if (apVM.Pagos.Any(a => a.FormaDePagoID == formaDePago.Id))
                {
                    ViewBag.Error = "La forma de pago ya está agregada.";
                    return View(apVM);
                }

                Pago pago = new Pago();
                pago.FormaDePago = _formasDePagoServicios.GetOne(formaDePago.Id);
                pago.FormaDePagoID = pago.FormaDePago.Id;
                apVM.Pagos.Add(pago);

                if (apVM.Pagos.Count == 1)
                {
                    apVM.Pagos.First().Monto = apVM.Total;
                }
            }
            else
            {
                Pago pago = new Pago();
                pago.FormaDePago = _formasDePagoServicios.GetOne(1);
                pago.FormaDePagoID = pago.FormaDePago.Id;
                apVM.Pagos.Add(pago);
                if (apVM.Pagos.Count == 1)
                {
                    apVM.Pagos.First().Monto = apVM.Total;
                }
                //Agregao la forma de pago Devolución
                if (System.Web.HttpContext.Current.Session["SaldoAFavor"] != null)
                {
                    decimal SaldoAFavor = decimal.Parse(System.Web.HttpContext.Current.Session["SaldoAFavor"].ToString());

                    Pago pagoDev = new Pago();
                    pagoDev.FormaDePago = _formasDePagoServicios.GetOne(4);
                    pagoDev.FormaDePagoID = pagoDev.FormaDePago.Id;
                    apVM.Pagos.Add(pagoDev);

                    apVM.Pagos[0].Monto = apVM.Total - SaldoAFavor;
                    apVM.Pagos[1].Monto = SaldoAFavor;

                }
                System.Web.HttpContext.Current.Session["ListaItemsVentaActual"] = apVM.Items;
            }

            return View(apVM);
        }

UI.Web/Views/Ventas/AgregarPago.cshtml
@model UI.Web.ViewModels.Ventas.VentasAgregarPagoViewModel
@using UI.Web.Helpers;
@{
    ViewBag.Title = "Agregar Pagos";
}

<script>
        // AUTOCOMPLETADO Clientes
        $(function () {

            $("html,body").css("overflow", "auto"); // Impide que el body modifique su tamaño al tipear en el textbox
            $("#TerminoBusquedaCliente").autocomplete({
                // El source del autocomplete es una acción de controlador
                source: function (request, response) {
                    $.ajax({
                        url: '@Url.Action("BusquedaClientes", "Clientes")',
                        type: 'GET',
                        dataType: 'json',
                        data: request,
                        success: function (data) {
                            if (!data.length) {
                                $("#ClienteIDAgregar").val(0);
                            }
                            response($.map(data, function (item) {
                                return { label: item.Nombre, id: item.Id };
                            }));
                        },
                    });
                },
                // Al seleccionar un resultado, seteamos los valores de clave y valor
                select: function (event, ui) {
                    $("#TerminoBusquedaCliente").val(ui.item.label);
                    $("#ClienteIDAgregar").val(ui.item.id);
                    //alert(ui.item.id)
                    return false;
                }
            }).autocomplete("widget").addClass("textbox-autocomplete");
        });

</script>
<div class="cabecera" style="margin-bottom: 20px;">
    Agregar Pagos
</div>

@using (Html.BeginForm("AgregarPago", "Ventas", FormMethod.Post, new { id = "form-venta" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-2">
                @Html.LabelFor(model => model.Cliente)
            </div>
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Cliente.Nombre, new { @class = "form-control", id = "TerminoBusquedaCliente", @placeholder = "Busqueda por apellido o DNI." })
                @Html.HiddenFor(model => model.ClienteID, new { id = "ClienteIDAgregar" })
                @Html.ValidationMessageFor(model => model.Cliente, "", new { @class = "text-danger" })
            </div>

        </div>
    </div>
        <hr />
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-2">
                        @Html.HiddenFor(model => model.Items)
                        @Html.LabelFor(model => model.FormaDePagoID)
                    </div>
                    <div class="col-md-3">@Html.DropDownListFor(model => model.FormaDePagoID, Model.FormasDePago, htmlAttributes: new { @class = "form-control" })</div>
                    <div class="col-md-3">
                        <button type="submit" id="btnAgregarFormaPago" value="agregarFormaPago" name="action:AgregarPago" class="btn btn-success" title="Agregar Pago">
                            <i class="glyphicon glyphicon-plus-sign"></i>
                        </button>
                    </div>

                </div>

            </div>

            <div class="row">
                <h3>
                    <label class="control-label" style="margin-left: 20px">
                        Total: $@Html.DisplayFor(model => model.Total)

                    </label>
                </h3>
            </div>

            <div class="row">
                <div class="col-md-5">
               
                    <table id="tabla-pagos" class="table table-bordered table-condensed table-responsive">
                        <thead>
                            <tr style="background-color:gainsboro; font-weight:bold">
                                <th hidden></th>
                                <th  style="text-align:center;">Forma de Pago</th>
                                <th  style="text-align:center;">Monto</th>
                                <th style="text-align:center;"></th>

                            </tr>
                        </thead>
                        <tbody style="background-color: #f9f9f9;">
                            @for (int i = 0; i < Model.Pagos.Count; i++)
                            {
                                <tr>
                                    <td hidden>
                                        @Html.TextBoxFor(item => Model.Pagos[i].FormaDePagoID)
                                        @Html.TextBoxFor(item => Model.Pagos[i].FormaDePago.Nombre)                            
                                        @Html.TextBoxFor(item => Model.Pagos[i].FormaDePago.Recargo)
                                    </td>
                                    <td style="text-align:center; width:250px">
                                        @Html.DisplayFor(item => Model.Pagos[i].FormaDePago.NombreRecargo, new { @readonly = "", @style = "border: 0px none; background-color: transparent;" })
                                     
                                    </td>
                                    <td class="acciones-fila-tabla form-inline" style="text-align:center; width:250px">
                                        @{
                                            if (Model.Pagos[i].FormaDePago.Recargo != 0 && Model.Pagos[i].FormaDePago.Recargo != 1)
                                            {
                                                @Html.DecimalFor(item => Model.Pagos[i].Monto, Model.Pagos[i].Monto, new { @id = @Model.Pagos[i].FormaDePagoID + "_" + @Model.Pagos[i].FormaDePago.Recargo, @class = "form-control monto recargo", style = "width: 100px", required = "required", placeholder = "$", min = 0 })
                                                <br />
                                            <text>Sub: </text>    @Html.Label(" ", new { id = @Model.Pagos[i].FormaDePagoID })

                                            }
                                            else
                                            {
                                                @Html.DecimalFor(item => Model.Pagos[i].Monto, Model.Pagos[i].Monto, new { @id = Model.Pagos[i].FormaDePagoID, @class = "form-control monto", style = "width: 100px", required = "required", placeholder = "$", min = 0 })
                                            }
                                        }
                                      
                                    </td>
                                    <td style="text-align:center">
                                        <a href="#" class="btn btn-danger btn-xs" onclick="AsignarID(@Model.Pagos[i].FormaDePagoID)" >
                                            <span class="glyphicon glyphicon glyphicon-trash"></span>
                                        </a>
                                        <button type="submit" style="visibility:hidden" name="action:EliminarFormaPago" id="btnEliminarFormaPago" value="@Model.Pagos[i].FormaDePagoID" class="btn btn-danger btn-xs">
                                            <i class="glyphicon glyphicon glyphicon-trash"></i>
                                        </button>
                                      
                                    </td>
                                </tr>
                            }
                            @*@Html.Hidden("ArticuloIDEliminar","", new { id = "ArticuloIDEliminar", name= "ArticuloIDEliminar" })*@
                            @Html.HiddenFor(model => Model.FormaPagoIDEliminar, new { id = "FormaPagoIDEliminar" })
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <table id="tabla-articulos" class="table table-bordered table-condensed table-responsive">
                    <caption><h4>Detalle</h4></caption>
                    <thead>
                        <tr style="background-color:gainsboro; font-weight:bold">
                            <th hidden></th>
                            <th>Art.</th>
                            <th>Cód.</th>
                            <th>Cant.</th>
                            <th style="text-align:center;">$</th>
                            <th style="text-align:center;">Desc.</th>
                            <th>Sub. $</th>
                        </tr>
                    </thead>
                    <tbody style="background-color: #f9f9f9;">
                        @for (int i = 0; i < Model.Items.Count; i++)
                {
                            <tr>
                                <td hidden>
                                    @Html.DisplayFor(item => Model.Items[i].ArticuloID)
                                </td>
                                <td>
                                    @Html.DisplayFor(item => Model.Items[i].Articulo.Nombre)
                                </td>
                                <td>
                                    -
                                </td>
                                <td style="text-align:center; width:20px">
                                    @Html.DisplayFor(item => Model.Items[i].Cantidad)

                                </td>
                                <td style="text-align:center; width:150px">
                                    @Html.DisplayFor(item => Model.Items[i].Precio)
                                </td>

                                <td class="acciones-fila-tabla form-inline" style="text-align:center; width:150px">
                                    @Html.DisplayFor(item => Model.Items[i].Descuento)

                                </td>
                                <td style="text-align:center; width:150px">
                                    @Html.DisplayFor(item => Model.Items[i].TotalItem)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
}
<div class="col-md-8">
    <div class="row form-inline">
        <button onclick="ValidarMonto()" class="btn btn-success" name="ConfirmarVenta" title="Confirmar Venta">
            <i class="glyphicon glyphicon-print"></i> Imprimir Ticket
        </button>

        @*<a href="@Url.Action("AgregarArticulo", "Ventas")" class="btn btn-primary">
                <span class="glyphicon glyphicon-backward"> Volver </span>
            </a>*@
      
        @using (Html.BeginForm("NuevaVenta", "Ventas", FormMethod.Post, new { id = "form-venta", @style = "margin-top:5px" }))
        {
            @Html.AntiForgeryToken()
            <button type="submit" id="btnAgregarArticulo" value="agregarArticulo" name="action:AgregarArticulo" class="btn btn-primary" title="Volver">
                <i class="glyphicon glyphicon-backward"> Volver</i>
            </button>
        }
    </div>
</div>


<script type="text/javascript">
    function AsignarID(id) {
        $("#FormaPagoIDEliminar").val("");
        $("#FormaPagoIDEliminar").val(id);
        $("#btnEliminarFormaPago").click();
    };

    function ValidarMonto() {
        var sum = 0;
        var total = "@Model.Total.ToString("#.##")";
        var res = total.replace(",", ".");
        $('.monto').each(function () {
            sum += parseFloat(this.value);

        });

        if ($('#ClienteIDAgregar').val() == 0) {
            swal("Oops...", "El Cliente no puede esta vacio.", "error");
            return false;
        }

        if (sum == res) {
            $('#form-venta').attr('action', '@Url.Action("ConfirmarVenta", "Ventas")').submit();
            return true;
        }
        else {

            swal("Oops...", "Los montos de los pagos no coinciden con el Total de la venta.", "error");
            return false;
        }
    };

    $(".recargo").blur(function () {
        var monto = $(this).val();
        var id = $(this).attr('id');
        var arrayID = id.toString().split('_');
        var inc = arrayID[1].replace(',', '.');
        var labelID = "#" + arrayID[0];
        var total = monto * inc;
        $(labelID).text(total);   
    });

</script>